[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling>=1.25" ]

[project]
name = "key-flip"
version = "0.1.0"
description = "key-flip is a utility that fixes text typed with the wrong keyboard layout."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
  { name = "Vlad Korneev", email = "veenrok@veenrok.com" },
]
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "typer>=0.20",
]
optional-dependencies.fmt = [
  "ruff>=0.14.5",
]
optional-dependencies.lint = [
  "ty>=0.0.1a26",
]
optional-dependencies.test = [
  "pytest>=9.0.1",
]
scripts.key-flip = "key_flip.cli.__main__:main"

[tool.ruff]
required-version = ">=0.11.12"
target-version = "py313"
line-length = 120
indent-width = 4

src = [ "src", "tests" ]
format.indent-style = "space"
format.quote-style = "double"
format.line-ending = "lf"
format.skip-magic-trailing-comma = false
format.docstring-code-line-length = 80
format.docstring-code-format = true
lint.select = [
  "C90",
  "E",
  "F",
  "I",
  "W",
]
lint.ignore = [  ]
lint.flake8-annotations.mypy-init-return = true
lint.flake8-annotations.suppress-none-returning = true
lint.flake8-bandit.check-typed-exception = true
lint.isort.section-order = [ "future", "standard-library", "third-party", "first-party", "local-folder" ]
lint.pydocstyle.convention = "pep257"

[tool.ty.environment]
root = [ "src", "tests" ]
python-version = "3.13"
